### PR TITLE
Rust solution

### PR DESCRIPTION
**Pull request by ispringle**
This is my Rust solution which does not use any crates

### CODE REVIEW

**Comment by drewpearce** [comment]
You have merge conflicts

**Comment by drewpearce** [comment]
Resolve conflicts plz

**Review by drewpearce — CHANGES_REQUESTED** [review]
resolve conflicts

**Comment by ispringle** [comment]
k, think something got merged after my fork's last merge with upstream. I'll fix it tomorrow, just ignore any commits in the meantime since I'll have to merge with upstream first

**Pull request merged**
