### PR TITLE
6502 lee

### PR DESCRIPTION
**Pull request by leebehrens**
Done at last. Unless I think of yet another tweak...

### CODE REVIEW

**Comment by plusuncold** [comment]
I've been trying to get this working in Docker for updating the leaderboard. I'm getting the following error:

```
Traceback (most recent call last):
  File "py65-golf201906/py65/monitor.py", line 30, in <module>
    from py65.devices.mpu6502 import MPU as NMOS6502
ModuleNotFoundError: No module named 'py65'
```

Do you know what going on here?

**Comment by leebehrens** [comment]
Forgot to include the __init__.py files in my patched version of Py65.

**Comment by leebehrens** [comment]
Patch with the missing files ready to merge.

**Comment by plusuncold** [comment]
I've applied the patch and tested again and get the same error. Do you have Docker that you can test this with?

(I've also renamed the `run_test.sh` file from `run-tests.sh` so that the python leaderboard script will be able to pick your solution up)

**Comment by leebehrens** [comment]
No, I don't. Not sure what the problem is. Downloaded it to a different machine, and getting the same error. 




After some poking around Py65, it appears its own source from GitHub also seems to be missing a couple files that Python wants, but aren't actually needed to run 6502 programs. I'll try stripping out some more and see if I can make it work. 




Thank you for your patience! 






On Wed, Jun 12, 2019 at 2:14 PM -0500, "plusuncold" <notifications@github.com> wrote:












I've applied the patch and tested again and get the same error. Do you have Docker that you can test this with?


(I've also renamed the run_test.sh file from run-tests.sh so that the python leaderboard script will be able to pick your solution up)

**Comment by leebehrens** [comment]
I was able to replicate the issue locally. After flattening Py65's directories, it successfully ran my challenge code (pony.bin).

**Pull request merged**
