### PR TITLE
Add cco3's solutions

### PR DESCRIPTION
**Pull request by cco3**

### CODE REVIEW

**Comment by plusuncold** [comment]
Could you do a couple of things before I pull this?
1) Rename the `run.sh` files to `run-test.sh` so the script can pick them up?
2) The run command for the gp version? I'm not familiar with it, is the << EOF \n EOF attempting to avoid having that in the `run.gp` file?

**Comment by cco3** [comment]
1. Yes, will do later.
2. It's just because .gp scripts typically launch into an interactive environment.  I don't think there's a flag not to do it.
3. The pari-gp package doesn't seem available on alpine, so it's not going to work...any chance we could switch to ubuntu or something else?

**Comment by cco3** [comment]
(Alternatively I guess I could update the dockerfile to pull in a binary directly)

**Comment by plusuncold** [comment]
I'd rather not mess around with Docker to get everything working again for Ubuntu.

If it's not possible to specify any part of that expression inside the script file I'm happy to pull it. Just doing due diligence to be fair to everyone!

**Comment by cco3** [comment]
OK, should be good to go now

**Comment by plusuncold** [comment]
I went to run this and it wouldn't run `gp` in Docker. Any ideas?

```
Sending build context to Docker daemon  80.46MB
Step 1/9 : FROM node:11-alpine
 ---> f34bcc2815ed
Step 2/9 : RUN apk update && apk add     bash     bc     build-base     cargo     dpkg     elixir     go     jruby     m4     python2     python3     ruby     rust     tar
 ---> Running in 2b2722640a4d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
v3.9.4-6-gce4b56ee80 [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.4-7-gcb4138ea5e [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 9770 distinct packages available
(1/87) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(2/87) Installing ncurses-terminfo (6.1_p20190105-r0)
(3/87) Installing ncurses-libs (6.1_p20190105-r0)
(4/87) Installing readline (7.0.003-r1)
(5/87) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(6/87) Installing bc (1.07.1-r0)
(7/87) Installing binutils (2.31.1-r2)
(8/87) Installing libmagic (5.36-r0)
(9/87) Installing file (5.36-r0)
(10/87) Installing gmp (6.1.2-r1)
(11/87) Installing isl (0.18-r0)
(12/87) Installing libgomp (8.3.0-r0)
(13/87) Installing libatomic (8.3.0-r0)
(14/87) Installing mpfr3 (3.1.5-r1)
(15/87) Installing mpc1 (1.0.3-r1)
(16/87) Installing gcc (8.3.0-r0)
(17/87) Installing musl-dev (1.1.20-r4)
(18/87) Installing libc-dev (0.7.1-r0)
(19/87) Installing g++ (8.3.0-r0)
(20/87) Installing make (4.2.1-r2)
(21/87) Installing fortify-headers (1.0-r0)
(22/87) Installing build-base (0.5-r1)
(23/87) Installing llvm-libunwind (5.0.2-r0)
(24/87) Installing llvm-libunwind-dev (5.0.2-r0)
(25/87) Installing rust-stdlib (1.31.1-r1)
(26/87) Installing libffi (3.2.1-r6)
(27/87) Installing llvm5-libs (5.0.2-r0)
(28/87) Installing rust (1.31.1-r1)
(29/87) Installing ca-certificates (20190108-r0)
(30/87) Installing nghttp2-libs (1.35.1-r0)
(31/87) Installing libssh2 (1.8.2-r0)
(32/87) Installing libcurl (7.64.0-r1)
(33/87) Installing libgit2 (0.27.7-r0)
(34/87) Installing cargo (1.31.1-r1)
(35/87) Installing xz-libs (5.2.4-r0)
(36/87) Installing xz (5.2.4-r0)
(37/87) Installing libbz2 (1.0.6-r6)
(38/87) Installing dpkg (1.19.2-r0)
(39/87) Installing erlang-kernel (21.2.1-r0)
(40/87) Installing erlang-stdlib (21.2.1-r0)
(41/87) Installing erlang-syntax-tools (21.2.1-r0)
(42/87) Installing erlang-parsetools (21.2.1-r0)
(43/87) Installing erlang-erl-interface (21.2.1-r0)
(44/87) Installing erlang-compiler (21.2.1-r0)
(45/87) Installing erlang (21.2.1-r0)
(46/87) Installing erlang-inets (21.2.1-r0)
(47/87) Installing erlang-crypto (21.2.1-r0)
(48/87) Installing erlang-asn1 (21.2.1-r0)
(49/87) Installing erlang-public-key (21.2.1-r0)
(50/87) Installing erlang-ssl (21.2.1-r0)
(51/87) Installing erlang-sasl (21.2.1-r0)
(52/87) Installing erlang-dev (21.2.1-r0)
(53/87) Installing erlang-dialyzer (21.2.1-r0)
(54/87) Installing erlang-erts (21.2.1-r0)
(55/87) Installing erlang-hipe (21.2.1-r0)
(56/87) Installing elixir (1.7.4-r0)
(57/87) Installing go (1.11.5-r0)
(58/87) Installing jruby-libs (9.2.0.0-r0)
(59/87) Installing openjdk8-jre-lib (8.212.04-r0)
(60/87) Installing java-common (0.1-r0)
(61/87) Installing p11-kit (0.23.14-r0)
(62/87) Installing libtasn1 (4.13-r0)
(63/87) Installing p11-kit-trust (0.23.14-r0)
(64/87) Installing java-cacerts (1.0-r0)
(65/87) Installing libjpeg-turbo (1.5.3-r4)
(66/87) Installing krb5-conf (1.0-r1)
(67/87) Installing libcom_err (1.44.5-r0)
(68/87) Installing keyutils-libs (1.6-r0)
(69/87) Installing libverto (0.3.0-r1)
(70/87) Installing krb5-libs (1.15.5-r0)
(71/87) Installing lcms2 (2.9-r1)
(72/87) Installing pcsc-lite-libs (1.8.24-r1)
(73/87) Installing lksctp-tools (1.0.17-r0)
(74/87) Installing openjdk8-jre-base (8.212.04-r0)
(75/87) Installing java-jffi-native (1.2.17-r0)
(76/87) Installing libc6-compat (1.1.20-r4)
(77/87) Installing jruby (9.2.0.0-r0)
(78/87) Installing m4 (1.4.18-r1)
(79/87) Installing expat (2.2.6-r0)
(80/87) Installing gdbm (1.13-r1)
(81/87) Installing sqlite-libs (3.26.0-r3)
(82/87) Installing python2 (2.7.16-r1)
(83/87) Installing python3 (3.6.8-r2)
(84/87) Installing yaml (0.2.1-r0)
(85/87) Installing ruby-libs (2.5.5-r0)
(86/87) Installing ruby (2.5.5-r0)
(87/87) Installing tar (1.32-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
Executing java-common-0.1-r0.trigger
OK: 874 MiB in 103 packages
Removing intermediate container 2b2722640a4d
 ---> d45b411497da
Step 3/9 : RUN touch /var/lib/dpkg/status
 ---> Running in 4128da310445
Removing intermediate container 4128da310445
 ---> 7d84f94249b5
Step 4/9 : RUN dpkg --configure -a
 ---> Running in ceba711ac837
Removing intermediate container ceba711ac837
 ---> efebacedb3bf
Step 5/9 : RUN wget http://mirrors.kernel.org/ubuntu/pool/universe/p/pari/pari-gp_2.11.0-1_amd64.deb
 ---> Running in 455f79afcb22
Connecting to mirrors.kernel.org (198.145.21.9:80)
Connecting to mirrors.edge.kernel.org (147.75.101.1:80)
pari-gp_2.11.0-1_amd  38% |************                    | 1216k  0:00:01 ETA
pari-gp_2.11.0-1_amd 100% |********************************| 3138k  0:00:00 ETA

Removing intermediate container 455f79afcb22
 ---> 1d11de14de43
Step 6/9 : RUN dpkg -i --force-all *.deb
 ---> Running in b05dc24b0165
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package architecture (amd64) does not match system (musl-linux-amd64)
Selecting previously unselected package pari-gp:amd64.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack pari-gp_2.11.0-1_amd64.deb ...
Unpacking pari-gp:amd64 (2.11.0-1) ...
Setting up pari-gp:amd64 (2.11.0-1) ...
dpkg: pari-gp:amd64: dependency problems, but configuring anyway as you requested:
 pari-gp:amd64 depends on libc6 (>= 2.14).
 pari-gp:amd64 depends on libgmp10.
 pari-gp:amd64 depends on libreadline7 (>= 6.0).
 pari-gp:amd64 depends on libx11-6.


Configuration file '/etc/gprc', does not exist on system.
Installing new config file as you requested.
Removing intermediate container b05dc24b0165
 ---> 91e6f9f3b5fc
Step 7/9 : RUN pip3 install six
 ---> Running in 9e99df5dea38
Collecting six
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.12.0
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 9e99df5dea38
 ---> 9f746cb842f3
Step 8/9 : COPY . /home/
 ---> 79f3082c8c6f
Step 9/9 : ENTRYPOINT python3 /home/run_tests.py
 ---> Running in 269ed26d5dc6
Removing intermediate container 269ed26d5dc6
 ---> 300e0c77c1e7
Successfully built 300e0c77c1e7
Successfully tagged challenge-2019-06:latest
Error loading shared library libX11.so.6: No such file or directory (needed by /usr/bin/gp)
Error relocating /usr/bin/gp: XDrawString: symbol not found
Error relocating /usr/bin/gp: __stpcpy_chk: symbol not found
Error relocating /usr/bin/gp: XClearWindow: symbol not found
Error relocating /usr/bin/gp: __strncpy_chk: symbol not found
Error relocating /usr/bin/gp: __longjmp_chk: symbol not found
Error relocating /usr/bin/gp: __fprintf_chk: symbol not found
Error relocating /usr/bin/gp: __printf_chk: symbol not found
Error relocating /usr/bin/gp: XSetFont: symbol not found
Error relocating /usr/bin/gp: __memcpy_chk: symbol not found
Error relocating /usr/bin/gp: XkbKeycodeToKeysym: symbol not found
Error relocating /usr/bin/gp: XCreateSimpleWindow: symbol not found
Error relocating /usr/bin/gp: XOpenDisplay: symbol not found
Error relocating /usr/bin/gp: __strcat_chk: symbol not found
Error relocating /usr/bin/gp: XDrawPoint: symbol not found
Error relocating /usr/bin/gp: XUnloadFont: symbol not found
Error relocating /usr/bin/gp: XDrawLine: symbol not found
Error relocating /usr/bin/gp: XCloseDisplay: symbol not found
Error relocating /usr/bin/gp: XGetErrorText: symbol not found
Error relocating /usr/bin/gp: XSetForeground: symbol not found
Error relocating /usr/bin/gp: XFillRectangle: symbol not found
Error relocating /usr/bin/gp: __pthread_register_cancel: symbol not found
Error relocating /usr/bin/gp: XFreeGC: symbol not found
Error relocating /usr/bin/gp: XDrawLines: symbol not found
Error relocating /usr/bin/gp: XDrawRectangle: symbol not found
Error relocating /usr/bin/gp: XNextEvent: symbol not found
Error relocating /usr/bin/gp: XSetWMProtocols: symbol not found
Error relocating /usr/bin/gp: XSetIOErrorHandler: symbol not found
Error relocating /usr/bin/gp: XMapWindow: symbol not found
Error relocating /usr/bin/gp: __strcpy_chk: symbol not found
Error relocating /usr/bin/gp: XCreateGC: symbol not found
Error relocating /usr/bin/gp: XSelectInput: symbol not found
Error relocating /usr/bin/gp: XLoadQueryFont: symbol not found
Error relocating /usr/bin/gp: XAllocColor: symbol not found
Error relocating /usr/bin/gp: XInternAtom: symbol not found
Error relocating /usr/bin/gp: XSetStandardProperties: symbol not found
Error relocating /usr/bin/gp: __sprintf_chk: symbol not found
Error relocating /usr/bin/gp: XSetErrorHandler: symbol not found
Error relocating /usr/bin/gp: XDrawPoints: symbol not found
Error relocating /usr/bin/gp: XChangeWindowAttributes: symbol not found
    Updating crates.io index
  Downloaded rug v1.4.0                                                         
  Downloaded gmp-mpfr-sys v1.1.13                                               
  Downloaded dirs v1.0.5                                                        
  Downloaded libc v0.2.57                                                       
   Compiling libc v0.2.57                                                       
   Compiling rug v1.4.0                                                         
   Compiling dirs v1.0.5                                                        
   Compiling gmp-mpfr-sys v1.1.13                                               
   Compiling fact v0.1.0 (/home/rust-plusuncold)                                
    Finished release [optimized] target(s) in 2m 08s                            
# command-line-arguments
loadinternal: cannot find runtime/cgo
[
  {
    "user": "cco3",
    "solution": "",
    "size": 26,
    "lang": "gp"
  },
  {
    "user": "pard68",
    "solution": "648",
    "size": 34,
    "lang": "pyth"
  },
  {
    "user": "sircharleswatson",
    "solution": "648",
    "size": 56,
    "lang": "elixir"
  },
  {
    "user": "patrickcarver",
    "solution": "648",
    "size": 57,
    "lang": "elixir"
  },
  {
    "user": "cco3",
    "solution": "648",
    "size": 57,
    "lang": "python"
  },
  {
    "user": "Kyle Nweeia",
    "solution": "648",
    "size": 59,
    "lang": "python"
  },
  {
    "user": "MatthewRDodds",
    "solution": "648",
    "size": 60,
    "lang": "ruby"
  },
  {
    "user": "Kyle Nweeia/pard68",
    "solution": "648",
    "size": 62,
    "lang": "bash"
  },
  {
    "user": "specs",
    "solution": "648",
    "size": 64,
    "lang": "python"
  },
  {
    "user": "plusuncold",
    "solution": "648",
    "size": 148,
    "lang": "rust"
  },
  {
    "user": "therecluse26",
    "solution": "648",
    "size": 210,
    "lang": "golang"
  }
]
```

**Comment by cco3** [comment]
Not totally sure here...I got the dockerfile building to the point that the command installed, but it may have been the wrong architecture (I had to force install because the amd64 string alpine was using didn't match the one in the package)...I'm not *that* familiar with docker, so I didn't get to the point where I had the tests actually running in docker.  (Everything always hung when I would run run_docker.sh, and wasn't sure if I was doing something wrong.)

**Pull request merged**
